### ISSUE TITLE
Search Members Node documentation is not complete

### ISSUE THREAD

**Issue by thauber** [mailchimp/mailchimp-client-lib-codegen#101]
Spec: Marketing, Section: search-members

What was unclear / unexpected / confusing: 

In the node example you do not clearly show how to add the other parameters into the call. I've tried adding them as an object, or adding them as subsequent arguments, but none of that yielded the correct resutlts:

Works, but doesn't allow me to filter by list:
```
mailchimp.searchMembers.search('hello@example.com').then((a)=>console.log(a.exact_matches))
```

Works, but doesn't filter by the list_id
```
mailchimp.searchMembers.search('hello@example.com', null, null, '<list_id>').then((a)=>console.log(a.exact_matches))
mailchimp.searchMembers.search('hello@example.com', {list_id: '<list_id>'}).then((a)=>console.log(a.exact_matches))
```

Doesn't work:
```
mailchimp.searchMembers.search({query: 'hello@example.com', list_id: '<list_id>'}).then((a)=>console.log(a.exact_matches))
```

**Comment by thauber** [comment]
I checked the source code to see that I should be using listId and not list_id

**Comment by bipol-mc** [comment]
Hey @thauber, thanks for the issue!  Glad you found the solution - will be closing this issue for now.

The code generation tool we're using will include some documentation for each function which hopefully helps with language specific situations like this: 
https://github.com/mailchimp/mailchimp-marketing-node/blob/68b3dcf53510572a6d9ae9ea5c92e837c1614ef1/src/api/SearchMembersApi.js#L87

In this case, these optional arguments are are keyed in camelCase.
