### ISSUE TITLE
Python code missing lowercasing email address

### ISSUE THREAD

**Issue by pawel-baster** [mailchimp/mailchimp-client-lib-codegen#113]
In at least one place in the documentation python sample code is missing a call to `.lower()` while generating subscriber hash, which causes problems if an email address contains capital letters. 

Link: https://mailchimp.com/developer/marketing/guides/create-your-first-audience/#check-a-contacts-subscription-status

Current python code: 
```member_email_hash = hashlib.md5(email.encode('utf-8')).hexdigest()```

For comparison see for instance PHP code, where `strtolower` is called:
```$subscriber_hash = md5(strtolower($email));```

**Comment by bipol-mc** [comment]
Thanks @pawel-baster!  

Closing this issue - just shipped an update to the guides which fixes the sample code.
