### ISSUE TITLE
Update the marketing PHP SDK readme to indicate it requires PHP v7+

### ISSUE THREAD

**Issue by PeteGrigg** [mailchimp/mailchimp-client-lib-codegen#119]
Any PHP version below 7.0.0 will not be able to load this library and this is not indicated anywhere that I can see, nor does composer throw any error or warning.

For example, the file .../composer/vendor/mailchimp/marketing/lib/Api/AuthorizedAppsApi.php has the following function:

`public function list($fields = null, $exclude_fields = null, $count = '10', $offset = '0')
 {
        $response = $this->listWithHttpInfo($fields, $exclude_fields, $count, $offset);
        return $response;
 }`

This will throw a parse error: `Parse error: syntax error, unexpected 'list' (T_LIST), expecting identifier (T_STRING) in .../composer/vendor/mailchimp/marketing/lib/Api/AuthorizedAppsApi.php on line 65`

This is due to "list" being a reserved PHP keyword. In PHP 7.0.0 they began allowing reserved keywords as class methods so this will not throw the error.

Could have saved a fair amount of time if the version requirement was indicated.

**Comment by Moishe** [comment]
Hey, sorry about that. The version is set in composer to >=7.2 but maybe that doesn't always work. Also added a line to the README, for both the marketing and transactional SDKs.
