### ISSUE TITLE
How to delete a webook when token has expired

### ISSUE THREAD

**Issue by desbrowne** [mailchimp/mailchimp-client-lib-codegen#120]
We have several past customers (i.e. they no longer pay us) that created webhooks from Mailchimp to our service.

If we have a valid auth token then we can delete the webhook, but in some situations, the token has expired.

I can't see in the webhook documentation how we cancel the webhooks if the auth token has expired?

For other services, we return HTTP code 410 (Gone), and that deletes the webhook.  Please clarify how to cancel Mailchimp webhooks in the above situation. Thanks.

**Comment by Moishe** [comment]
Hi there! This has been fixed; here's the relevant release note: https://mailchimp.com/developer/release-notes/returning-410-from-audience-webhook-will-disable-it/

Note that this is for *audience* webhooks. Batch API webhooks are a different codepath, but they also need a valid token to initiate and they're transient, unlike audience webhooks which are permanent.
