### ISSUE TITLE
Add orders/carts with customer.id longer than 50 chars returns 404 Page Not Found

### ISSUE THREAD

**Issue by humphrey** [mailchimp/mailchimp-client-lib-codegen#128]
Spec: Marketing, Section: ecommerce-orders

What was unclear / unexpected / confusing: 

There is very little explained about what the customer.id field is used for in orders and carts.

Firstly, the documentation just mentions that this is a string, but if longer than 50 characters, a 404 page not found error is returned.  This is not explained in the documentation.  I literally had to copy and paste the json that was failing from my program into a REST client, and continue making random changes until it was accepted.  The API responses or documentation do not give any indication as to what the error could be.

Another issue is that the documentation does not explain what the customer id is used for.  I cannot use my own id, because if the customer changes their email address, the API returns error messages that explain how a customers email address cannot be changed.  Therefore, when syncing carts, my solution was to concatenate my customer id with their email address.  Then I avoided the "cannot change email address" error message if the email address changes.  However, by doing this my id's are often longer than 50 chars, and therefore MailChimp returns a 404 status code.

Some better explanations of what a customer is and what these objects are used for, and what a customer id is, would make integrating much quicker.

**Comment by Moishe** [comment]
Merged this PR https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/132 which adds some documentation and also annotates these fields in Swagger as having a maximum length of 50 characters. Also changed the code on the backend to return a 400 and a more informative error message.

**Comment by humphrey** [comment]
Awesome 😍
