### ISSUE TITLE
Increase the number of records to return for the getListMembersInfoWithHttpInfo method

### ISSUE THREAD

**Issue by DuffmanRound** [mailchimp/mailchimp-client-lib-codegen#129]
Spec: Marketing, Section: authorized-apps

What was unclear / unexpected / confusing: 
There is a way in which you can increase the $ count parameter to 2000 or it only has to be 1000 the maximum value.

My audiences are 5000 contacts and it is useless if I can only get 1000.

**Comment by bipol-mc** [comment]
Hey @DuffmanRound -

We use our `offset` and `count` fields to offer pagination, you can find more information in [our documentation[(https://mailchimp.com/developer/marketing/docs/methods-parameters/#pagination).

You can retrieve 1000 records at a time, so you'd want 5 calls, the first with `offset` of 0, then `1000`, etc.

**Comment by DuffmanRound** [comment]
Very good, thank you very much for the information @bipol-mc. 
Regards!
