### ISSUE TITLE
Unsure how to request fields in get_list_members_info

### ISSUE THREAD

**Issue by pawel-baster** [mailchimp/mailchimp-client-lib-codegen#135]
Spec: Marketing, Section: list-members

What was unclear / unexpected / confusing: 

I am trying to retrieve a list of email addresses for members of a list using Python, but from the documentation, example and docstring it's not clear to me how to do it. Without using `fields` argument I get a list of dictionaries each of them containing i. a. `email_address` key. But if I try to retrieve just this one field using any of the following calls:
```
client.lists.get_list_members_info(list_id, fields=['email_address'])
client.lists.get_list_members_info(list_id, fields='email_address')
client.lists.get_list_members_info(list_id, fields=['email'])
```
all I get is:
```<Response [200]>```

**Comment by bipol-mc** [comment]
Hey @pawel-baster -

I believe the correct fields parameter should be `fields=['members.email_address']`.  The [response](https://mailchimp.com/developer/marketing/api/list-members/list-members-info/) from the `lists-members-info` endpoint is wrapped by an outer `members` envelope in this case.

**Comment by bipol-mc** [comment]
Awesome!

We have some documentation on the [fields and exclude_fields](https://mailchimp.com/developer/marketing/docs/methods-parameters/#partial-responses) parameters in a guide (which definitely may be hard to find).  Will make a note for us to think on better ways to communicate these features.

Thanks for submitting an issue @pawel-baster!  Closing for now.
