### ISSUE TITLE
Ping curl command is misleading

### ISSUE THREAD

**Issue by justuseapen** [mailchimp/mailchimp-client-lib-codegen#137]
Spec: Marketing, Section: ping

What was unclear / unexpected / confusing: 

```
curl -X GET \
  https://server.api.mailchimp.com/3.0/ping \
  -H 'authorization: Basic <USERNAME:PASSWORD>'
```

really that <USERNAME:PASSWORD> should be <API_KEY>

Further, the getting started guides use the `curl --user` flag and I think might be syntactically incorrect. DIdn't work for me in any case.

**Comment by bipol-mc** [comment]
Hey @justuseapen, thanks for the issue!

Closing in favor of https://github.com/mailchimp/mailchimp-client-lib-codegen/issues/24 -- I notice that the `cURL` snippets in the getting started guide has backticks, which I believe is invalid syntax - will get that updated as well.  

Thanks again!
