### ISSUE TITLE
automation endpoints and automation dashboard appear not to be in sync

### ISSUE THREAD

**Issue by yivi** [mailchimp/mailchimp-client-lib-codegen#139]
Spec: Marketing, Section: automation

What was unclear / unexpected / confusing: 
Automations listed on Automation -> Customer Journey ->  My Customer Journeys are not necessarily returned (or maybe even managed) by this part of the API.

E.g. I get this on the dashboard:
https://cln.sh/MPh3V0

And yet I get this when I call the `list` endpoint:
https://cln.sh/er5GFw

**Comment by yivi** [comment]
Apparently the endpoint covers "classic automations", but no "customer journeys".
But the equivalent endpoints for "customer journeys" either do not exist or are not documented, nor the difference between the two.

**Comment by mc-hannah-morrison** [comment]
Hi @yivi ! 
Equivalent endpoints for Customer Journeys have not been added yet, but I passed this thread along to that team.

Thanks for pointing out that the API documentation didn't specify which automation types are supported. We've updated it to note that those endpoints are for classic automations. https://mailchimp.com/developer/marketing/api/automation/
