### ISSUE TITLE
Member tags not being sent by mailchimp-marketing-python

### ISSUE THREAD

**Issue by pencerw** [mailchimp/mailchimp-client-lib-codegen#141]
Hey all, I'm having an issue with a simple API (adding an active tag to a member) call using mailchimp-marketing-python. I believe everything is set up correctly and I get a 204 response, but when I confirm that member's tags there are none. See below, noting the last bit in the final response:

`>>> mailchimp_api_key = REDACTED
>>> theprepared_list_id = REDACTED
>>> email_id = REDACTED
>>>
>>> client = MailchimpMarketing.Client()
>>> client.set_config({
>>> 	"api_key": mailchimp_api_key,
>>> 	"server": mailchimp_service_prefix
>>> })
>>>
>>> response = client.lists.update_list_member_tags(theprepared_list_id, email_id, {"name": "clicked_on_memberships_link", "status": "active"})
>>> print(response)
<Response [204]>
>>>
>>>
>>> response = client.lists.get_list_member(theprepared_list_id, email_id)
>>> print(response)
{'id': REDACTED, 'email_address': REDACTED, 'unique_email_id': '6135566265', 'web_id': 257741541, 'email_type': 'html', 'status': 'subscribed', 'merge_fields': {'FNAME': '', 'LNAME': '', 'TEXTYUI_3': '', 'TEXT2': '', 'WEBSITEYU': '', 'TEXTAREAY': ''}, 'interests': {'09c88d7ba2': False, 'f99df0b13c': False, '2befcfde9c': False, '7147e5f28a': False}, 'stats': {'avg_open_rate': 0.0323, 'avg_click_rate': 0.0054}, 'ip_signup': '8.36.86.121', 'timestamp_signup': '2017-10-09T19:23:57+00:00', 'ip_opt': '67.170.31.59', 'timestamp_opt': '2017-10-09T19:24:18+00:00', 'member_rating': 4, 'last_changed': '2017-10-09T19:24:18+00:00', 'language': '', 'vip': False, 'email_client': 'Android webview', 'location': REDACTED, 'marketing_permissions': [{'marketing_permission_id': 'dd6eaff78a', 'text': 'Email me', 'enabled': False}], 'source': 'Squarespace', 'tags_count': 0, 'tags': [], ...}`

**Comment by Moishe** [comment]
Hi there! I think the `body` param is wrong, it should be (formatted to make the example more readable):

```
{
  "tags": [
    {
      "name": "clicked_on_memberships_link",
      "status": "active"
    }
  ]
}
```

Lemme know if that works (or not)! Pretty sure it will -- I tried it out to verify.

**Comment by Moishe** [comment]
Agree, the docs (specifically the sample code) could be improved -- feel free to open another issue about that!
