### ISSUE TITLE
Member tagging reference doesn't fully specify how to pass tags

### ISSUE THREAD

**Issue by pencerw** [mailchimp/mailchimp-client-lib-codegen#145]
see https://github.com/mailchimp/mailchimp-client-lib-codegen/issues/141#issuecomment-820400073

**Comment by bipol-mc** [comment]
Hey @pencerw -

We updated the code snippets for the tags endpoint to properly encode the response body we were expecting.  Not sure if this was the additional clarification you were seeking, or if you had some other ideas!

Really appreciate the feedback!

**Comment by pencerw** [comment]
much better, thanks!
