### ISSUE TITLE
Python code uses `is` operator instead of `==` for string literal comparison

### ISSUE THREAD

**Issue by rtr3** [mailchimp/mailchimp-client-lib-codegen#151]
When using the python generated package, there's a syntax warning that pops up:

`env/lib/python3.9/site-packages/mailchimp_transactional/api_client.py:77: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if method is 'POST':`

**Comment by Moishe** [comment]
Thanks for catching this! Fixed in https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/152
