### ISSUE TITLE
curl: (6) Could not resolve host: server.api.mailchimp.com

### ISSUE THREAD

**Issue by davidfriedl** [mailchimp/mailchimp-client-lib-codegen#16]
When trying to use 

```BASH 
  curl -X GET \
  'https://server.api.mailchimp.com/3.0/' \
  -H 'authorization: Basic <USERNAME:PASSWORD>'
```
the server responds with

`curl: (6) Could not resolve host: server.api.mailchimp.com`

Is the server down or is an activation needed? I followed the [Api Docs](https://mailchimp.com/developer/api/marketing/root/list-api-root-resources/) but can't figure out the error.

**Comment by dcts** [comment]
`server` needs to be replaced with your region. For example `us19`. 

> To find the value for the server parameter used in mailchimp.setConfig, log into your Mailchimp account and look at the URL in your browser. You’ll see something like https://us19.admin.mailchimp.com/ — the us19 part is the server prefix. Note that your specific value may be different.

See more here: [Postmark Quick Start Documentation](https://mailchimp.com/developer/guides/marketing-api-quick-start/#make-your-first-api-call).
