### ISSUE TITLE
Export APi

### ISSUE THREAD

**Issue by andrewhilson** [mailchimp/mailchimp-client-lib-codegen#17]
Spec: Marketing

What was unclear / unexpected / confusing: Where are the docs for the Export API? Is this deprecated?

**Comment by mc-hannah-morrison** [comment]
Hi @andrewhilson ! Sorry that documentation has been unavailable, it wasn't immediately migrated with our new documentation launch.
We now have Export API documentation back up: https://mailchimp.com/developer/marketing/docs/export-api/
