### ISSUE TITLE
members to the list

### ISSUE THREAD

**Issue by HateBunnyPlzzz** [mailchimp/mailchimp-client-lib-codegen#174]
Spec: Marketing, Section: lists

What was unclear / unexpected / confusing:  In the previous docs there was clearly mentioned email_address, stats, email_type body parameters which are absolutely absent in the new updated docs, I am still unable to find the mentioned ones, hence I am having difficulty in creating a newsletter sign-up webpage using the MailChimp mailing API...
Please look into this issue and if any help is available I would appreciate it, thank you

**Comment by bipol-mc** [comment]
Hey @HateBunnyPlzzz --

The [POST /lists/{list_id}/members](https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/) documentation should describe the fields that you are describing here (for use when needing to add members to a given list.
![image](https://user-images.githubusercontent.com/55551473/121021424-5f5a9000-c76f-11eb-8076-1ab0fd941a16.png)

Apologies if I'm misunderstanding, and I hope that this helps!

**Comment by bipol-mc** [comment]
Hey @HateBunnyPlzzz  - going to close this issue for now, but please feel free to reopen (or add to the existing thread if this problem is still oustanding).  

Thanks!!
