### ISSUE TITLE
We updated the campaign template through the marketing api, but it still uses the old template content.

### ISSUE THREAD

**Issue by elvisshih** [mailchimp/mailchimp-client-lib-codegen#176]
We use the 'campaigns.update' method to update the campaign template like below
```
const response = await client.campaigns.update("campaign_id", {
    recipients: ...
    settings: {
      ...
      template_id: xxxxx
    },
  });
```
And we can see the response was successful and template_id was changed,
but when we sign in to Mailchimp and view the draft campaign, the template content is old.

**Comment by mc-hannah-morrison** [comment]
Hello!
For an issue like this that isn't a problem with the SDK itself, but the behavior of application data, I recommend reaching out to our support team: https://mailchimp.com/help/mailchimp-support-options/
They can help take a look at your account for clues. Thanks!
