### ISSUE TITLE
PHP SDK: Missing GuzzleHttp\Psr7 functions

### ISSUE THREAD

**Issue by SPie** [mailchimp/mailchimp-client-lib-codegen#193]
[GuzzleHttp\Psr7](https://github.com/guzzle/psr7) released its new `2.0` version today. In this version, all the functions in the `GuzzleHttp\Psr7` namespace were removed.
And because the required `guzzlehttp/guzzle` requires version  `^1.7 || ^2.0` a composer update could use the newest version which will break functionality in the Mailchimp PHP SDK because the `GuzzleHttp\Psr7\build_query` function doesn't exist anymore.
Maybe the required `guzzlehttp/guzzle` version should be `< 7.3` or `guzzlehttp/psr7` should be locked at `< 2.0`.
Otherwise `GuzzleHttp\Psr7\build_query` should be replaced with `GuzzleHttp\Psr7\Query::build()`.

**Comment by mc-hannah-morrison** [comment]
Ah thank you, I see what you mean! I added the dependency on guzzlehttp/psr7 < 2.0 for now, but happy to revisit if needed and maybe replace those calls
