### ISSUE TITLE
marketingAPI, PHP: Getting Click and Open reports for Automations

### ISSUE THREAD

**Issue by hectovs** [mailchimp/mailchimp-client-lib-codegen#196]
It appears that automations can be treated like campaigns. Although when calling 

 $client->reports->getCampaignClickDetails($campaign_id, null, null, 1000, 0, null);
 $client->reports->getCampaignOpenDetails($campaign_id, null, null, 1000, 0, null );

with $campaign_id being the id of the automation, there is no Open or Click data returned for either. I'm not sure if this is functionality that simply isn't available but it'd be very useful to be able to access an automation's  click and open data through the API  in a similar way to the way it can be accessed for campaigns.

If it's of any consequence the automation that I am trying to do this for is currently paused.

**Comment by mc-hannah-morrison** [comment]
Hi! For questions about underlying data and behavior, you can reach out to our Support team. They'll be able to look at your automations, and handle functionality requests.
