### ISSUE TITLE
Disable GuzzleHTTP exceptions

### ISSUE THREAD

**Issue by prtuson** [mailchimp/mailchimp-client-lib-codegen#202]
I have just started integrating the mailchimp API with our application which is built on the Joomla CMS and is in php 7.2.
I have found the mailchiimp API excellent with very good documentation and easy to install and integrate in with Joomla.
My problem is the use of the guzzlehttp tool. When the mailchimp API returns an error, guzzlehttp turns it into an exception and crashes the website. It also cuts short  the message provided by mailchimp.
For example, when I add a new member to a list. If that member already exists then the website crashes.
My question is: From within mailchimp can I disable the execption handling provided by guzzlehtttp so that I have direct access to the message provided by mailchimp?
My way around this at the moment is:

        try {
            $response = self::$client->lists->addListMember($listId, $data);
        } catch (exception $e) {
            if (preg_match('/{.*/', $e->getMessage(), $matches) {
                $match = (strpos($matches[0], '}') !== false) ? $matches[0] : $matches[0] . '"}';
                $resp = json_decode($match);
                $response = ($resp->title === 'Member Exists') ? true : $match;
            }
        }
        return $response;

Note that I have to find the json code within the message from guzzlehttp and then repair it.

**Comment by prtuson** [comment]
Hello,

Please, can someone let me know how to stop guzzle messing up mailchimp responses using php?

I need to make progress.

**Comment by bipol-mc** [comment]
Hey @prtuson - 

As you stated, this is a default property of the guzzle client, and the expected use of the Mailchimp PHP client library is to catch these exceptions as you're doing in the example.  

You should be able to transform the error response body into a php object like this: 
```php
json_decode($e->getResponse()->getBody()->getContents(), true) 
```

as an example: 
```php
try {
    $response = $mailchimp->lists->addListMember('d3ea431ecb', [
        "email_address" => "Christopher.Nolan@gmail.com",
        "status" => "pending",
    ]);
} catch (\GuzzleHttp\Exception\RequestException $ex) {
    print_r(json_decode($ex->getResponse()->getBody()->getContents(), true));
}
```
```sh
mailchimp-php % php test.php
Array
(
    [title] => Member Exists
    [status] => 400
    [detail] => Christopher.Nolan@gmail.com is already a list member. Use PUT to insert or update list members.
    [instance] => cb0f493e-d77a-eeb9-ef7e-56ad30644c08
)
```

**Comment by prtuson** [comment]
Hello,

Thank you very much, that is so much better.

Regards,

Peter

**Comment by bipol-mc** [comment]
Awesome, closing this issue!

**Comment by tomsommer** [comment]
Would be nice if it instead threw a ApiException if it is indeed a valid request, and not a Guzzle-exception which could mean anything.
