### ISSUE TITLE
In the PHP SDK MARKETING ecommerce->addCartLineItem duplicate an a existing cart

### ISSUE THREAD

**Issue by cristianlabadie** [mailchimp/mailchimp-client-lib-codegen#210]
I was working using this endpoint and instead add new cart line in existing cart, the endpoint duplicate the cart
![Captura de Pantalla 2021-07-26 a la(s) 15 52 39](https://user-images.githubusercontent.com/42389014/127050259-2e7a57d6-b11f-4e8d-abf5-4c6597dce9b6.png)
![Captura de Pantalla 2021-07-26 a la(s) 15 53 18](https://user-images.githubusercontent.com/42389014/127050334-61d9b341-98b0-4b2d-bd7a-07caef6d240e.png)

**Comment by mc-hannah-morrison** [comment]
Hello! I recommend reaching out to Mailchimp's support team. They can take a look at your account and see whats happening.
