### ISSUE TITLE
Bug with mailchimp-marketing-node createListMemberEvent method and propertie body with characters like Ñ

### ISSUE THREAD

**Issue by unxavi** [mailchimp/mailchimp-client-lib-codegen#212]
Hi,

I'm integrating our system with MailChimp to send our emails from user events with your service.

I have realize that we have a problem with this method  https://mailchimp.com/developer/marketing/api/list-member-events/add-event/ and passing properties.

When we call the method like this:

```
await mailchimp.lists.createListMemberEvent(
    listId,
    hash,
    {
      name: "eventName",
      properties: {
        location: "Atlanta",
        lastName: "Doe"
      }
    }
  );
```

Everything is working as expected and we see the properties on the user events and can use them on the emails.

But when we include a character like a Ñ.

```
await mailchimp.lists.createListMemberEvent(
    listId,
    hash,
    {
      name: "eventName",
      properties: {
        location: "Lipeñes",
        lastName: "Doe"
      }
    }
  );
```

Then the event gets sent, but the properties are all empty. I believe this also happens for accents: áéíóú

For other methods, like `addListMember` this is working correctly on the `merge_fields`, but not for the events.

Thanks a lot for your help.

**Comment by mc-hannah-morrison** [comment]
Hello! We recommend reaching out to Mailchimp's support team for help. They're best equipped to take a look at whats happening with data in your account.

**Comment by unxavi** [comment]
@mc-hannah-morrison I did Mailchimp reach support team, they told me there was a bug on the library, that they could not do anything about. They were aware about this bug and developers already knew about it, but there was not ETA available when it would be fixed.

Pherhaps you should leave this issue open for when the team decide to fix it.

**Comment by unxavi** [comment]
@mc-hannah-morrison if you wish I can post here the transcript of the chat about this with the support team. To be honest I'm  disappointed that the event API is not compliance with other language beside English alphabet.
