### ISSUE TITLE
get_list_recent_activity shows only last 10 days

### ISSUE THREAD

**Issue by iopkelvin** [mailchimp/mailchimp-client-lib-codegen#218]
There is no parameter like count. So It is impossible to request list activity data up to 180 days when it only returns the latest 10 days by default.

**Comment by mc-hannah-morrison** [comment]
Thanks for reporting! You're right, although the endpoint does accept count & offset, it was left out of the spec so didn't make it into the SDK and docs. 
This has now been fixed
