### ISSUE TITLE
mailchimp-transactional-ruby Template Info has type error

### ISSUE THREAD

**Issue by FreekingDean** [mailchimp/mailchimp-client-lib-codegen#22]
Looks like when calling `client.templates.info` the api changed from just taking the slug to taking the name as a hash passed.

I think it would benefit having methods that take 1 argument just have a standard parameter, OR if a parameter is required to use keyword arguments. IE:
```
class Templates
  def info(name:)
  end
end
``` 

This would result in a very clear error that the name argument was not passed. Swagger should support generating these methods from the api spec.

**Comment by mtashley** [comment]
Hi @FreekingDean, we've taken note of your proposal and appreciate your feedback.

**Comment by FreekingDean** [comment]
Does  that mean this is not being implemented or it is? Sorry I'm not understanding the response.
