### ISSUE TITLE
Audience webhook documentation unclear

### ISSUE THREAD

**Issue by CollinAlpert** [mailchimp/mailchimp-client-lib-codegen#232]
Spec: Marketing, Section: list-webhooks

What was unclear / unexpected / confusing: 
It would be helpful to know what kind of request will be made to my URL when the webhook fires. Is it a GET/POST request? If it's a POST request, what's in the body for e.g. the campaign webhook?

**Comment by bipol-mc** [comment]
Hey @CollinAlpert 

We have a [guide](https://mailchimp.com/developer/marketing/guides/sync-audience-data-webhooks/) which may be helpful in understanding the `list-webhooks` endpoint.  You should expect a `POST` with a `application/x-www-form-urlencoded` body.  We show an example of the response from the `subscribes` and `unsubscribes` event in this guide as well - for campaign, you'd expect the existing envelope described for `subscribe` and `unsubscribe`, but with the data field containing: `id`, `subject`, `status`, and a `reason` field if the `status` is not `sent`.

**Comment by bipol-mc** [comment]
Ah, I see.  Unfortunately, I don't believe that the `campaign` webhook would help here, unless you made a further query to [GET /campaigns/.../](https://mailchimp.com/developer/marketing/api/campaigns/get-campaign-info/), and checked the `recipient` field for the accompanying list/segment options.  From there, you could query all members for that given list/

**Comment by CollinAlpert** [comment]
Nice tip with the segment members! I'll check that out, thanks.
