### ISSUE TITLE
curl examples could be misleading

### ISSUE THREAD

**Issue by bipol-mc** [mailchimp/mailchimp-client-lib-codegen#24]
Mailchimp offers a [guide](https://mailchimp.com/developer/guides/marketing-api-quick-start/#make-your-first-api-call) on crafting your first API call, and one of the code examples uses `curl`:
```sh
# install jq: https://stedolan.github.io/jq/download/

dc="YOUR_DC"
apikey="YOUR_API_KEY"

curl -sS \
  "https://${dc}.api.mailchimp.com/3.0/ping" \
  --user "`anystring`:${apikey}" | jq -r
```

Mailchimp also provides auto-generated `curl` examples for each of the reference api requests:
```sh
curl -X GET \
  https://server.api.mailchimp.com/3.0/automations/{workflow_id}/emails \
  -H 'authorization: Basic <USERNAME:PASSWORD>'
```

I think it'd make sense to reconcile the reference documentation `curl` snippets to use `--user`, since 
Basic authentication implies `base64` encoding, username can be anything, and password must be the users apikey. Making the `server` portion a bit more explicit to indicate that the caller's `dc` is required might make sense too.

**Comment by rtshilston** [comment]
I support this issue.  I only managed to make successful curl requests by finding this Github issue, and it showing me what I should be using for username/password, and that it needs base64 encoding.

**Comment by bipol-mc** [comment]
This should be fixed.  Closing for now!
