### ISSUE TITLE
When querying members by date, timezone is ignored

### ISSUE THREAD

**Issue by dregad** [mailchimp/mailchimp-client-lib-codegen#241]
### What issue did you have?

The *List members info* API calls accepts various date query parameters. According to [documentation](https://mailchimp.com/developer/marketing/api/list-members/list-members-info/), these should be provided in ISO 8601 time format (`2015-10-21T15:41:36+00:00`), but the API is actually not considering the timezone.

Baseline: _since_last_changed_  in UTC (or date given without timezone):
```
$ DATE=2021-09-02T10:00:00+00:00
$ curl -s --user "anystring:$APIKEY" "https://$DC.api.mailchimp.com/3.0/lists/$LIST/members?fields=members.last_changed&sort_field=last_changed&since_last_changed=$DATE" |jq -r .members[].last_changed
2021-09-02T10:48:33+00:00
2021-09-02T15:01:50+00:00
2021-09-02T15:01:52+00:00
```

Test: _since_last_changed_  in UTC-2 **FAILS** (it returns the same data as UTC)
```
$ DATE=2021-09-02T10:00:00-02:00
$ curl -s --user "anystring:$APIKEY" "https://$DC.api.mailchimp.com/3.0/lists/$LIST/members?fields=members.last_changed&sort_field=last_changed&since_last_changed=$DATE" |jq -r .members[].last_changed
2021-09-02T10:48:33+00:00
2021-09-02T15:01:50+00:00
2021-09-02T15:01:52+00:00
```

Expected results for UTC-2 (`2021-09-02T10:00:00-02:00` == `2021-09-02T12:00:00+00:00`)
```
2021-09-02T15:01:50+00:00
2021-09-02T15:01:52+00:00
```

**Comment by sarahjanemorris** [comment]
Hello @dregad - so sorry for the delay here. Your best bet here would be to [write into our support team](https://mailchimp.com/help/mailchimp-support-options/) to help you troubleshoot. Closing this issue.

**Comment by dregad** [comment]
@sarahjanemorris I don't understand why you're redirecting me to your support team here.

I think I have clearly demonstrated, with detailed steps for your to reproduce the issue, that the API does not behave according to the documentation, i.e. there's a bug. With all due respect, I believe _you_ should be taking this up to your engineering or support team so they fix the issue.

For the record, I don't see the need to *troubleshoot* anything on my end, as I have already implemented a workaround for that bug in my code.

Thanks.
