### ISSUE TITLE
"VIP status" link goes to langauges help

### ISSUE THREAD

**Issue by vetcovetco** [mailchimp/mailchimp-client-lib-codegen#244]
Spec: Marketing, Section: list-members

What was unclear / unexpected / confusing:
Under Audiences > Members > Add Member to List > Expand > `vip`
 "VIP status" link goes to https://mailchimp.com/help/view-and-edit-contact-languages/

**Comment by mc-hannah-morrison** [comment]
Oops, you're right there was a mistake there. Thanks for reporting! We've updated it now
