### ISSUE TITLE
PHP Marketing API "no member" calls throw exception rather than returning error in JSON

### ISSUE THREAD

**Issue by mc2** [mailchimp/mailchimp-client-lib-codegen#25]
I'm syncing data between apps. There are accounts in those apps both in and not in a Mailchimp list.

When I call a PHP API method with an hashed email not in Mailchimp, for example the simplest call to see if a member exists `...->lists->getListMember()`
The response from the method is an empty string, and an exception is fired
`$e->getMessage()`:
```text
Client error: `GET https://[...].api.mailchimp.com/3.0/lists/[...]/members/[...]?fields=status` resulted in a `404 Not Found` response:
{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","st (truncated...)
```
From the docs, https://mailchimp.com/developer/api/marketing/list-members/delete-list-member/, I am expecting a PHP object from the JSON: 
```json
{
  "type": "https://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/#404",
  "title": "Resource Not Found",
  "status": 404,
  "detail": "The requested resource could not be found.",
  "instance": "995c5cb0-3280-4a6e-808b-3b096d0bb219"
}
```
I get similar exceptions from `deleteListMemberPermanent()`, `updateListMember()`, etc.

Given the code generation of this API, if this can't be changed/corrected, please add a note to the docs somehow (which I assume are generated as well...) At least in https://github.com/mailchimp/mailchimp-marketing-php, please. Thanks!

**Comment by bipol-mc** [comment]
Hey @mc2!

It seems that this is a default [Guzzle behavior](https://docs.guzzlephp.org/en/stable/quickstart.html#exceptions), where `400` level errors are thrown as exceptions.  

Definitely can add this to the readme I think to give a heads up to users, and appreciate the note here!

Closing for now, feel free to add more details to the thread or open a new issue if needed.

**Comment by yamenarahman** [comment]
To get full error response. https://stackoverflow.com/questions/53862823/error-logging-is-truncated-in-laravel-of-guzzle-http/68395775#68395775
