### ISSUE TITLE
Misleading limitations

### ISSUE THREAD

**Issue by lvalladares** [mailchimp/mailchimp-client-lib-codegen#27]
In this page: https://eepurl.com/dyil9E you talk about a limit in the Bulk Actions of an Audience after sending a campaign, but nothing is mentioned in the Batch or Members API.

How does this work? I cant add/remove/update list members through API following the same limitation criteria or this does not affect the API?

Also, there is any limit in the amount of operations in one batch request? This is not stated anywhere.

**Comment by mtashley** [comment]
Please see the following developer guide for detailed instructions on implementing batch operations - [Run Requests Asynchronously with the Batch Endpoint](https://mailchimp.com/developer/guides/run-async-requests-with-the-batch-endpoint/)
