### ISSUE TITLE
I have a problem in mailchimp

### ISSUE THREAD

**Issue by vicnava14** [mailchimp/mailchimp-client-lib-codegen#277]
Spec: Marketing, Section: file-manager-files

What was unclear / unexpected / confusing: 

I have a problem in mailchimp, I am getting an error and I don't know why the error shows me the following message

Pop-up forms and product retargeting emails require mailchimp for PrestaShop 1.0.3 or later
Please verify your plugin is up to date

I want to know how I can solve it

**Comment by sarahjanemorris** [comment]
Hey @vicnava14,  your best bet here would be to [write into our support team](https://mailchimp.com/help/mailchimp-support-options/) and ask to speak to one of our API specialists.

**Comment by sarahjanemorris** [comment]
Closing this issue now.
