### ISSUE TITLE
ApiClient class not found in mailchimp-transactional-php

### ISSUE THREAD

**Issue by karelvasicek** [mailchimp/mailchimp-client-lib-codegen#29]
`mailchimp-transactional-php` is installed via composer, but `ApiClient` class cannot be auto-loaded.

Issue seems to be related to https://github.com/mailchimp/mailchimp-transactional-php/blob/f226000c232fec6424defba8b0722b641767b955/composer.json#L19-L21

`Configuration.php` file is not renamed and thus auto-loading of the `ApiClient` class does not work.

**Comment by mtashley** [comment]
The reported issue above has been resolved as part of PR https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/42
