### ISSUE TITLE
Language parameter on POST/ PUT / PATCH

### ISSUE THREAD

**Issue by troels-athenas** [mailchimp/mailchimp-client-lib-codegen#38]
Spec: Marketing, Section: list-members

What was unclear / unexpected / confusing: 

I can give 'language' as a parameter, but it doesn't seem to do anything.
What does "If set/detected, the subscriber's language." even mean?

Have tried feeding it with Group name, Group id and stuff like 'en'. No luck.

In general, all examples in this doc leaves the more advanced options blank or empty.

**Comment by bipol-mc** [comment]
@troels-athenas really appreciate the feedback, and apologies for the super late turnaround.  

At the time this post was made, we were removing embedded links from the docs, which we've just [added back](https://mailchimp.com/developer/marketing/api/list-members/add-member-to-list/).  The docs are still confusing here, but they now link out to our [guide to editing contact languages](https://mailchimp.com/help/view-and-edit-contact-languages/).  

Setting this to one of the valid language codes in the guide should add this to the contact's language field in their profile - `en` should have been a valid language in this case.
