### ISSUE TITLE
API endpoints have unclear methods

### ISSUE THREAD

**Issue by scodeler** [mailchimp/mailchimp-client-lib-codegen#41]
Spec: Marketing, Section: list-member-tags

What was unclear / unexpected / confusing: 
Docs doesn't show us how to pass the tag array.
Also I can't manage to update tags by calling the method `updateListMemberTags`, and it returns null, without throwing any errors

**Comment by HikariSenshi** [comment]
Also It is unclear how to get list of all possible tags from my profile.

**Comment by mtashley** [comment]
Duplicate issue of Issue https://github.com/mailchimp/mailchimp-client-lib-codegen/issues/23 - Please see the current guidance in the thread.
