### ISSUE TITLE
How do I find the authentication method?

### ISSUE THREAD

**Issue by dhyani15** [mailchimp/mailchimp-client-lib-codegen#47]
Spec: Marketing, Section: lists

What was unclear / unexpected / confusing: I am not able to see the authentication method.

**Comment by mtashley** [comment]
Please see the [Marketing API Quick Start](https://mailchimp.com/developer/guides/marketing-api-quick-start/) guide for instructions on using Basic Auth with the marketing client libraries. Additionally, you can use OAuth2 and instructions can be found at [Access Data on Behalf of Other Users with OAuth 2](https://mailchimp.com/developer/guides/access-user-data-with-oauth-2/).
