### ISSUE TITLE
Placing a store order

### ISSUE THREAD

**Issue by Darkelf151** [mailchimp/mailchimp-client-lib-codegen#48]
Spec: Marketing, Section: orders

What was unclear / unexpected / confusing: 

The given code snippet flat out doesn't work as listed - it returns a 400 error every time. There is no description about what fields are required, or the order in which things must be done to make it work and the error reporting is less than useless. 

A simple flow diagram such as "create store -> add product lines -> add order " would be the very least that should be described in the docs, along with a clear marking of required vs optional fields.
Whoever wrote the api docs did so with a clear understanding that anybody reading them already knew how the API was structured and what fields were required to make things work.

**Comment by bipol-mc** [comment]
Hey @Darkelf151 -

Thanks for the feedback here!  We recently shipped some [e-commerce](https://mailchimp.com/developer/marketing/docs/e-commerce/#the-basics) documentation that goes over each of the various models that are required to build out an e-commerce integration. 

 I think the prose here should help with understanding the various expectations around the e-commerce endpoints, but definitely open to more feedback if this is still not sufficient!
