### ISSUE TITLE
Member specific activity feed is not very useful, need an overall activity feed

### ISSUE THREAD

**Issue by berkcoker** [mailchimp/mailchimp-client-lib-codegen#55]
Spec: Marketing, Section: list-member-activity-feed

What was unclear / unexpected / confusing: 
There needs to be an overall activity feed where start and end dates can be specified. Member specific activity feed is pretty much useless when you need activity across campaigns and when you have thousands of members in a list.

**Comment by mc-hannah-morrison** [comment]
Hello! I recommend sending this request to our support team. They can better route this feature request to the right place.
