### ISSUE TITLE
Incorrect Get parameter for /lists/{list_id}/segments

### ISSUE THREAD

**Issue by prg011** [mailchimp/mailchimp-client-lib-codegen#58]
Spec: Marketing, Section: list-segment-members

What was unclear / unexpected / confusing: It says that one of the Query Parameters for GET is "fields". This is incorrect. It should say "include_fields".

**Comment by mc-hannah-morrison** [comment]
Hello!
"fields" is the correct query parameter in Marketing API endpoints for filtering the response to only particular fields.

We can note "include_fields" may be more expected, but no plans to change the parameters currently. Thanks!

**Comment by prg011** [comment]
My bad indeed.
