### ISSUE TITLE
Create tags when publishing new releases

### ISSUE THREAD

**Issue by dregad** [mailchimp/mailchimp-client-lib-codegen#59]
I'm evaluating the [Marketing API for PHP](https://github.com/mailchimp/mailchimp-marketing-php), which I include in my project via Composer as documented in the README file.

I have a problem with [the way you publish the library to Packagist](https://packagist.org/packages/mailchimp/marketing), as it can't be installed without specifying a stability level of _dev_:
```
 $ composer require mailchimp/marketing

  [InvalidArgumentException]
  Could not find a version of package mailchimp/marketing matching your minim
  um-stability (stable). Require it with an explicit version constraint allow
  ing its desired stability.
```

If I set requirement in composer.json to `"mailchimp/marketing": "*"` as instructed, I get:
```
 $ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for mailchimp/marketing * -> satisfiable by mailchimp/marketing[dev-master].
    - Removal request for mailchimp/marketing == 9999999-dev
```

I do not want to (cannot, actually) use ` "minimum-stability": "dev"` for obvious reasons, so I updated requirement to `"mailchimp/marketing": "@dev"`, which works as expected:
```
 $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing mailchimp/marketing (dev-master e08b0f7): Cloning e08b0f7f4e from cache
Generating autoload files
```

So IMO you should at the very least **update the installation instructions in the README file**.

Using `@dev` is still a problem however, because I need to be able to control the actual version that gets installed. This setting will install the newest release (from _master_ branch) whenever `composer update` is run. Our internal processes require proper and formal testing of new releases, so this is not good.

It would be better to **create Git tags for new releases**, this way Composer requirement can be defined with a specific version, e.g. `~3.0.19` or `^3.0`.

Thanks for your consideration.

**Comment by dregad** [comment]
It would appear that since #45 [you *are* creating the tag](https://github.com/mailchimp/mailchimp-client-lib-codegen/blob/712035b81c7df8a8c564fbbfd4825154645b87a1/.github/workflows/create-release-marketing.yml#L516), but it's not getting pushed to the target repo.

Maybe add the `--tags` option to the `git push` statement at line 517 (and of course the same in create-release-transactional.yml) ?

**Comment by mtashley** [comment]
The reported issue has been resolved as of commit https://github.com/mailchimp/mailchimp-client-lib-codegen/commit/e6c1572f49fdc6650f8a1d50f2e8cb161512afd2 Thank you for your feedback!

**Comment by dregad** [comment]
@mtashley great, thanks for the fast response and fixing this issue.

[Packagist](https://packagist.org/packages/mailchimp/marketing) now lists the latest 3.0.22 release, so the README install instructions work as currently published. 

Following best practice I would recommend to update the Composer requirement to `~3.0` instead of `*`.
