### ISSUE TITLE
API documentation issues

### ISSUE THREAD

**Issue by lewing728** [mailchimp/mailchimp-client-lib-codegen#65]
Am going through the tutorials on Marketing and Transactional APIs. With the Marketing tutotiral for Node.js it has the first line as `import mailchimp from "@mailchimp/mailchimp_marketing";` however this does not work - says that import can only be used in modules, but if I used `const mailchimp = require("@mailchimp/mailchimp_marketing")` it worked. Not sure if that is a me problem at which point ignore :-) This can be seen on https://mailchimp.com/developer/guides/marketing-api-quick-start/ under Make Your First API Call.

With the Transactional API tutorial I noticed that the npm install is incorrect at least for the Node.JS instructions. It says to `npm install mailchimp-transactional` however, when you try to run that it says it cannot be found. If you do `npm install @mailchimp/mailchimp_transactional` it works and I was able to get through the remainder of the tutorial. This can be seen on https://mailchimp.com/developer/guides/transactional-api-quick-start/ under Install the client library for your language.
Just thought I'd let someone know so they can update the tutorial. Other than that the tutorial is easy to understand and go through but those hiccups did cause some delay in getting through it.

**Comment by mtashley** [comment]
Hi @lewing728, this issue should be resolved now, thank you for you feedback!
