### ISSUE TITLE
Is it possible to set a Proxy with the PHP client ?

### ISSUE THREAD

**Issue by dregad** [mailchimp/mailchimp-client-lib-codegen#66]
Trying to execute code in a corporate environment behind an HTTP proxy, I get timeouts as the client is not able to access the Mailchimp server.

Is there a way to set the proxy ?

**Comment by dregad** [comment]
Anyone ?

**Comment by mc-hannah-morrison** [comment]
We don't currently provide a way to set the proxy without modifying the library, but you can set it in the guzzle request options https://docs.guzzlephp.org/en/stable/request-options.html#proxy

**Comment by dregad** [comment]
Thanks for your reply, although I must admit it's somewhat disappointing to wait for 9 months, only to get a "won't fix" reply in the end... 

We'd rather avoid having to maintain our own fork of the library, and hope you'll reconsider usage behind a corporate proxy in the future.
