### ISSUE TITLE
Problems with the `fields` and `exclude_fields` parameters

### ISSUE THREAD

**Issue by dregad** [mailchimp/mailchimp-client-lib-codegen#67]
## Format of `fields` and `exclude_fields` parameters

The API reference documents both parameters as string arrays, but this is not consistent with the description, which mentions a _comma-separated list of fields_:

> fields string[]
A comma-separated list of fields to return. Reference parameters of sub-objects with dot notation.
>
>exclude_fields string[]
A comma-separated list of fields to exclude. Reference parameters of sub-objects with dot notation. 

What I observe is that passing an array does not work, while using a comma-delimited string does:
```php
$mc = new MailchimpMarketing\ApiClient();

$mc->lists->getListInterestCategories($list_id, 'categories.id,categories.title');
$mc->lists->getListInterestCategories($list_id, ['categories.id,categories.title']);
// both of the above calls work as expected, i.e. return a list of categories with the 2 specified fields,

$mc->lists->getListInterestCategories($list_id, ['categories.id','categories.title']);
// DOES NOT WORK: returns a list with only the title (id field is eaten) - I would expect to see both fields
```

## Combining of `fields` and `exclude_fields` parameters

I also noticed that `fields` and `exclude_fields` seem to be mutually exclusive, but this is not documented
```php
$mc->lists->getListInterestCategories($list_id, 'categories', null);
// returns the categories array, as expected

$mc->lists->getListInterestCategories($list_id, null, 'categories._links');
// excludes the categories links but displays other fields (total_items, etc), as expected

$mc->lists->getListInterestCategories($list_id, 'categories', 'categories._links');
// DOES NOT WORK: returns the the full record as if neither fields nor exclude_fields were defined
// I would expect to see just the categories array's fields (list_id, id, title, display_order, type) without the links
```
Is it possible to combine the two parameters ? If so, how ? Documentation should be updated.

**Comment by bipol-mc** [comment]
Hey @dregad -

Thanks for submitting this issue.  On your first point in regards to how the arguments are being parsed, it seems like we are not properly encoding arrays into the query parameter values.  I'll be looking into this.

You can't combine `fields` and `exclude_fields`, [they are mutually exclusive](https://mailchimp.com/developer/marketing/docs/methods-parameters/#partial-responses) and passing in both will return indeterminate behavior.  It'd definitely make sense on our side to make this more explicit, either with further information in our documentation, additional verbiage in the field description, or returning an error if both fields are passed in.

FWIW, in your categories example, you could achieve the response your expecting by enumerating the categories fields and eliding _links, e.g. `fields=categories.list_id,categories.id,categories.title,categories.display_order,categories.type`.

**Comment by dregad** [comment]
@bipol-mc Thanks for your feedback

> it seems like we are not properly encoding arrays into the query parameter values. I'll be looking into this.

Looking forward to seeing the fixes

> You can't combine `fields` and `exclude_fields`, [they are mutually exclusive](https://mailchimp.com/developer/marketing/docs/methods-parameters/#partial-responses)

Not sure if the docs were in the same state back in October last year when I submitted the issue, but if they were I probably misunderstood the _or_ as "logical" (and/or) instead of exclusive.

> It'd definitely make sense on our side to make this more explicit, either with further information in our documentation, additional verbiage in the field description, or returning an error if both fields are passed in.

If you could do that, it would be great.

> in your categories example, you could achieve the response you're expecting by enumerating the categories fields and eliding _links

Indeed enumerating all fields is precisely what I did to achieve the desired results.

That said, it would be nice and convenient to be able to combine both parameters. Would you consider this as a possible future enhancement ?

**Comment by bipol-mc** [comment]
Hey @dregad,

`3.0.35` of the php lib should have fixed this issue.  It seems like `swagger-codegen` doesn't parse the `collectionFormat` for fields anymore, so I've added that to fix the `fields` and `exclude_fields` parameters.

Haven't added anything to the documentation just yet, but that will likely be a followup to this work.  

And on allowing the combination - I can definitely see how both properties could be used to reduce toil (in your example, give me all the category fields with the exception of the links, without having to know precisely what fields are in the object), but I think we'll hold of on implementation of this improvement until we see some more feedback.

Thanks again for reporting this issue - your extremely descriptive responses have been super helpful!  Closing for now.  Feel free to continue this discussion on this thread!

**Comment by dregad** [comment]
> I can definitely see how both properties could be used to reduce toil (in your example, give me all the category fields with the exception of the links, without having to know precisely what fields are in the object)

You got that exactly right

> we'll hold of on implementation of this improvement until we see some more requests for this sort of thing

OK fair enough, it would have been nice to have but I can live without it. Hopefully it will become part of some future release.

Glad I could help, and thanks for your support :smiley:
