### ISSUE TITLE
Cosmetic issue: typo in query parameter description

### ISSUE THREAD

**Issue by grimsa** [mailchimp/mailchimp-client-lib-codegen#71]
Spec: Marketing, Section: list-members

What was unclear / unexpected / confusing: 

Section: `Add or update list member` (and also `Add member to list`)
Query parameter: `skip_merge_validation`

Text: `... This defaults to False. Possible values: or .` (should be "Possible values: true or false"?)

**Comment by bipol-mc** [comment]
Hey @grimsa - 

Thanks for submitting this issue.  The field description should now be updated in the docs, with a bit more detail on what exactly this field does!
