### ISSUE TITLE
"Conditions" aren't detailed anywhere in the API docs

### ISSUE THREAD

**Issue by cweagans** [mailchimp/mailchimp-client-lib-codegen#74]
POST /campaign
PATCH /campaign/[id]
GET /campaign/[id]

All of these have recipients.segment_opts.conditions[] and none of them have any details about what objects might need to go inside that array.

Halp?

**Comment by reinefjord** [comment]
They were detailed in the previous version of the docs, it's weird that they are not there anymore. The different values weren't explained though, so you hade to guess what they meant.

If you don't have a large and diverse data set on your account where you can see what the different values can be, it's pretty much impossible to use some endpoints.

**Comment by reinefjord** [comment]
I was actually able to find the conditions in the Swagger spec: [spec/marketing.json](https://github.com/mailchimp/mailchimp-client-lib-codegen/commit/99f7c888c3e62f07f54251a6e55333f2214dc4d9#diff-3b538ac76a5d591c7d63cb4e843283d0d2afaacfe673f5b192ff49f934410592)

They are on line 63936, or with `jq`:
```
jq '.paths."/lists/{list_id}/segments/{segment_id}".get.responses."200".schema.properties.options.properties.conditions' marketing.json
```

**Comment by bipol-mc** [comment]
Closing this for now - we provide an [Alternative Schemas](https://mailchimp.com/developer/marketing/docs/alternative-schemas/#segment-condition-schemas) guide which describes the segment conditions now.  We're still fixing up the documentation here (we can definitely add some further explanation around each activity), I hope this helps though!
