### ISSUE TITLE
/lists/{list_id}/segments does not return all tags

### ISSUE THREAD

**Issue by rdamehta-understood** [mailchimp/mailchimp-client-lib-codegen#79]
Spec: Marketing, Section: list-segment

What was unclear / unexpected / confusing: I was trying to get info on all the tags for a particular list_id, and i noticed in the that not all the tags in mailchimp ui show up in the json response

is there another a endpoint for tags?

**Comment by bipol-mc** [comment]
Hey @rdamehta-understood - 

The [lists-segments](https://mailchimp.com/developer/api/marketing/list-segments/list-segments/) endpoint is intended to show all the tags created for a given list.  

Do you have any sample code you could share, perhaps a screenshot of what you're seeing in the UI, and a `JSON` body of the API output?

**Comment by mc-hannah-morrison** [comment]
Closing due to age, but feel free to repoen
