### ISSUE TITLE
Search members, misunderstanding and improvements.

### ISSUE THREAD

**Issue by ortegafernando** [mailchimp/mailchimp-client-lib-codegen#80]
Spec: Marketing, Section: search-members

What was unclear / unexpected / confusing: please, write down that it only search in EMAIL, FNAME and LNAME. Nothing more.
It will be great that it can search in merge fields (even customs ones) and TAGS

Thanks

**Comment by bipol-mc** [comment]
Hey @ortegafernando!

Thanks for the feedback here - the documentation is [updated](https://mailchimp.com/developer/marketing/api/search-members/search-members/), specifically the description of what goes into the query parameter.
