### ISSUE TITLE
Code sample doesn't show syntax for adding actual tags

### ISSUE THREAD

**Issue by dima7k** [mailchimp/mailchimp-client-lib-codegen#82]
Would be great to see actual tags being added in the code sample, as opposed to just calling the method

**Comment by bipol-mc** [comment]
We've recently updated the documentation which should now be rendering the POST body for `lists-members-tags` https://mailchimp.com/developer/marketing/api/list-member-tags/add-or-remove-member-tags/

The `cURL` snippet isn't properly rendered just yet, but the other languages should be presented correctly.  Closing for now!
