### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by SuvorovAndrey** [mailchimp/mailchimp-client-lib-codegen#84]
Spec: Marketing, Section: list-member-tags

What was unclear / unexpected / confusing:

The example is not showing a code of how the developer has to write to add a tag to the member. Unfortunately, 90% of the documentation is too simple, unclear, and difficult to understand. In the documentation when there is a title Body parameters, it is unclear that in that moment we have to add an object body: {} with its parameters. It will be better to add the following description after each title "Body parameters", and add an example to the code, like so (for NodeJS):
`await mailchimp.lists.updateListMemberTags("list id (audience id)", "email hash", {
              body: {
                tags: [{name: "The created or a new tag name", status:'active'}]
              }
            });`

Please include the sample code with a specific tag to add.  Another thing, with CURL we can add user to the specific tag if we know the tag id,

**Comment by bipol-mc** [comment]
In the case of handling body parameters - we weren't correctly noting that the body parameter was required for updating member tags, and several other endpoints. 

We fixed this in https://github.com/mailchimp/mailchimp-client-lib-codegen/pull/90 - I believe this resolved the issue described here.

Thank you for leaving some feedback - going to close this issue for now, please feel free to reopen if needed!
