### ISSUE TITLE
About adding multiple members at once

### ISSUE THREAD

**Issue by ValleyFish** [mailchimp/mailchimp-client-lib-codegen#86]
Hello, how can I add multiple members while calling the api only once? I found the api / lists / {list_id} / members to add members once, but I didn't find the function to add multiple members.

**Comment by mc-hannah-morrison** [comment]
Hello @ValleyFish ! You can add multiple members using a single call with this endpoint:
https://mailchimp.com/developer/api/marketing/lists/batch-subscribe-or-unsubscribe/
