### ISSUE TITLE
Limited conditions accepted for list-preview-segment

### ISSUE THREAD

**Issue by nathanhebe** [mailchimp/mailchimp-client-lib-codegen#94]
Spec: Marketing, Section: list-preview-segment

What was unclear / unexpected / confusing: 
It appears as though the only segment conditions you can pass to `/3.0/lists/{list_id}/preview-segment` are `SignupSource` & `LandingPageActivity`.

When attempting to pass through valid segment conditions (directly passed from a campaign webhook), we get the following error messages...

```
You passed in an invalid condition_type. Only SignupSource and LandingPageActivity are currently supported.
You passed in an invalid field. Only source is currently supported.
The value you selected is not a valid choice.
```

Example body for preview-segment request
```
{
      "match": "all",
      "conditions": [
        {
          "condition_type": "EmailAddress",
          "field": "EMAIL",
          "op": "contains",
          "value": "test"
        }
      ]
    }
```

**Comment by michael-heard-mc** [comment]
Hi Nathan, 

Thanks for commenting. We don't have any immediate plans to expand the capability of this endpoint but its in our backlog. Other than `EmailAddress` are there any other conditions you'd like to segment on? I can note them.

**Comment by bipol-mc** [comment]
Closing this issue - @nathanhebe feel free to add details per michael's comment to this thread!
