### ISSUE TITLE
Make /reports/{campaign_id}/click-details return unique links

### ISSUE THREAD

**Issue by GhostyJade** [mailchimp/mailchimp-client-lib-codegen#95]
Spec: Marketing, Section: click-reports

What was unclear / unexpected / confusing: 
I've ran a campaign with 4 links. (and those are reported correctly on the mailchimp website ui)
When I try to get the link's list every entry is returned twice.
How can I prevent getting dupicates?
Thanks

**Comment by mc-hannah-morrison** [comment]
Hello! I recommend reaching out to our support team with this kind of question. They can help look into issues with the data returned by the API.
