### ISSUE TITLE
Please document how to Create a Product Retargeting Email with a Custom API 3.0 Integration

### ISSUE THREAD

**Issue by humphrey** [mailchimp/mailchimp-client-lib-codegen#97]
Spec: Product Retargeting Email
What was unclear / unexpected / confusing: 

[This page](https://mailchimp.com/help/create-a-product-retargeting-email/) explains that you can Create a Product Retargeting Email with a custom API 3.0 integration.  However, nowhere in the API 3.0 documentation does it explain how it works, or how to set that up with a custom API 3.0 integration. All links for more information just go to generic api pages that don't answer the questions a developer needs to know to create an integration.

For example: theses question needs to be explained in the docs:

**How does Mailchimp know which pages a user a visited on your site?*  *

**How do I configure my store to tell mailchimp which products a customer has visited?* *

As there isn't an API v3.0 endpoint to do this, I suspect there must be an analytics-esk script that reports to mailchimp who has visited which products.

After many hours of trawling through documents AND THE SOURCE CODE OF THE WOO-COMMERCE PLUGIN, I have discovered there is a [Connect Site Script](https://mailchimp.com/developer/marketing/api/ecommerce-stores/get-store-info/) in the store endpoint.  I assume this is the analytics style JavaScript that I am looking for, but nowhere explains how to use this, what it does, or even if this is what I am looking for.

**Comment by bipol-mc** [comment]
Hey @humphrey, thanks for the feedback here.

We recently pushed some [E-commerce documentation](https://mailchimp.com/developer/marketing/docs/e-commerce/#product-retargeting-emails) changes which goes into how to set up Product Retargeting, as well as some of our other e-commerce features.

**Comment by humphrey** [comment]
> Hey @humphrey, thanks for the feedback here.
> 
> We recently pushed some [E-commerce documentation](https://mailchimp.com/developer/marketing/docs/e-commerce/#product-retargeting-emails) changes which goes into how to set up Product Retargeting, as well as some of our other e-commerce features.

Awesome!  Thank you for updating that!  It makes sense now :)
