### ISSUE TITLE
skip_merge_validation - parameter definition misleading/confusing

### ISSUE THREAD

**Issue by ameotoko** [mailchimp/mailchimp-client-lib-codegen#99]
Spec: Marketing, Section: marketing/api/list-members/

Endpoints "Add member to list", "Add or update list member", "Update list member" accept `skip_merge_validation` parameter, which is defined as 'Type: boolean' with possible values `true` or `false`.

**What needs to be documented** is that PHP client library accepts this argument **as a string**, not boolean type.

```php
// Usage according to the docs (doesn't work):
$response = $client->lists->addListMember("list_id", [], true);

// How it actually works:
$response = $client->lists->addListMember("list_id", [], 'true');
```

This might also be the case for other libraries, but I only use PHP, so can't tell for sure.

**Comment by bipol-mc** [comment]
Thanks for the issue!

We will be shipping [an update](https://mailchimp.com/developer/release-notes/handling-boolean-query-parameters/) that ensures we are handling the boolean values we're sending from the client libraries. In this case, guzzle is converting the boolean value to the query parameter value `1`, which wasn't being properly handled by the endpoints.

**Comment by bipol-mc** [comment]
The API should now properly handle `true` and `"true"` values.

Closing for now!
